[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7.3"
cortex-m-semihosting = "0.5.0"
embedded-hal = "1.0.0"
heapless = "0.8.0"
panic-halt = "0.2.0"
panic-semihosting = "0.6.0"
stm32f4xx-hal = { version="0.10", features=["stm32f407"]}
