[package]
name = "library"
version = "0.1.0"
edition = "2021"

[features]
# デフォルトで有効になるフィーチャ
default = ["parallel", "serde"]

# 依存関係を持たないフィーチャ
special = []

# 依存関係をもつフィーチャ
parallel = ["crossbeam"]

# 依存クレートのフィーチャを有効にするフィーチャ
nightly = ["crossbeam/nightly"]

# いろいろな依存関係を混ぜた例
full = ["crossbeam/nightly", "parallel", "serde"]

[dependencies]
crossbeam = {version = "0.7.3", optional = true}
serde = {version = "1.0.111", optional = true}
